#!/usr/bin/env python3
"""One-off: assemble top-5 prim galleries + relocate all referenced charts into the vault.

This script:
  1. Reads /data/all_trades_dataset.csv (3,300 rows)
  2. Identifies top-5 enter_tags by trade count
  3. For each top-5 tag: picks ~20 representative trades (outcome-stratified), copies their
     PNGs into obsidian_trade_journals/assets/charts/<Strategy>/, and writes
     obsidian_trade_journals/Research/galleries/<tag>/gallery.md
  4. Scans every .md file in the vault for existing chart embeds pointing at
     ../../../data/all_trade_charts/...; copies those PNGs into the vault and rewrites the
     embed paths to vault-internal locations

Idempotent. Re-runnable. Does NOT touch git.

Constraints (per user spec):
  - Top-5 prims only (no full 3,300 backfill)
  - Renderer is COPY only, not re-render — uses existing PNGs as ground truth
  - Throttled (process spawns 1 worker; no parallel CPU spike)
"""
from __future__ import annotations

import csv
import re
import shutil
import sys
from collections import Counter, defaultdict
from pathlib import Path

VAULT = Path(__file__).resolve().parent.parent
SRC_DATA = VAULT.parent / "data"
SRC_CHARTS = SRC_DATA / "all_trade_charts"
CSV_PATH = SRC_DATA / "all_trades_dataset.csv"
ASSETS = VAULT / "assets" / "charts"
GALLERIES = VAULT / "Research" / "galleries"

TOP_N_PRIMS = 5
TRADES_PER_GALLERY = 20

# Outcome buckets we want represented in each gallery (where available)
OUTCOME_BUCKETS = ["clean_win", "noisy_win", "missed_continuation",
                   "bad_entry_good_idea", "fast_loss", "slow_loss", "scratch"]


def load_rows() -> list[dict]:
    with CSV_PATH.open() as f:
        rows = list(csv.DictReader(f))
    for r in rows:
        for k in ("profit_ratio", "mfe_pct", "mae_pct"):
            try:
                r[k] = float(r[k])
            except (TypeError, ValueError):
                r[k] = 0.0
    return rows


def pick_representative(trades_for_tag: list[dict], n: int) -> list[dict]:
    """Pick up to n trades, stratified by outcome. Return in chronological order."""
    by_outcome: dict[str, list[dict]] = defaultdict(list)
    for t in trades_for_tag:
        by_outcome[t.get("outcome", "")].append(t)
    chosen: list[dict] = []
    # Round-robin across outcome buckets in priority order until we have n
    bucket_iters = [(k, iter(sorted(by_outcome[k], key=lambda r: abs(r["profit_ratio"]), reverse=True)))
                    for k in OUTCOME_BUCKETS if by_outcome.get(k)]
    while len(chosen) < n and bucket_iters:
        next_round = []
        for k, it in bucket_iters:
            if len(chosen) >= n:
                break
            try:
                chosen.append(next(it))
                next_round.append((k, it))
            except StopIteration:
                pass
        bucket_iters = next_round
    return chosen


def copy_chart(rel_chart_path: str) -> Path | None:
    """Copy data/all_trade_charts/X/Y.png → vault/assets/charts/X/Y.png. Return new path."""
    src = SRC_DATA / rel_chart_path[len("all_trade_charts/"):] if rel_chart_path.startswith("all_trade_charts/") else SRC_DATA / rel_chart_path
    if not src.exists():
        # Try as fully-qualified path under data/
        src = SRC_DATA / rel_chart_path
    if not src.exists():
        return None
    rel_inside = src.relative_to(SRC_CHARTS)
    dst = ASSETS / rel_inside
    dst.parent.mkdir(parents=True, exist_ok=True)
    if not dst.exists():
        shutil.copy2(src, dst)
    return dst


def fmt_pct(v: float) -> str:
    return f"{v*100:+.2f}%"


def write_gallery(tag: str, sample: list[dict]) -> Path:
    galdir = GALLERIES / tag
    galdir.mkdir(parents=True, exist_ok=True)
    path = galdir / "gallery.md"

    lines: list[str] = [
        "---",
        f'title: "Prim Gallery — {tag}"',
        "type: prim-gallery",
        "updated: 2026-04-25",
        "status: active",
        f"enter_tag: {tag}",
        f"sample_size: {len(sample)}",
        "selection_rule: outcome-stratified across {clean_win, noisy_win, missed_continuation, bad_entry_good_idea, fast_loss, slow_loss, scratch}",
        "---",
        "",
        f"# {tag}",
        "",
        f"Representative sample of {len(sample)} trades drawn from the full library "
        f"(`enter_tag = {tag}`). Charts were generated by the upstream all-trades pipeline; "
        "this page only embeds them. Selection is outcome-stratified to surface failure modes "
        "alongside winners — not a top-N-by-PnL list.",
        "",
        "## Trade index",
        "",
        "| # | Strategy | Pair | open_date | profit | MFE | MAE | outcome | exit_diagnosis |",
        "|---:|---|---|---|---:|---:|---:|---|---|",
    ]
    embeds: list[str] = []
    for i, t in enumerate(sample, 1):
        # Path inside vault
        rel_chart = t.get("chart_path", "")
        if rel_chart.startswith("all_trade_charts/"):
            rel_inside = rel_chart[len("all_trade_charts/"):]
        else:
            rel_inside = rel_chart
        # gallery.md is at obsidian_trade_journals/Research/galleries/<tag>/
        # asset is at obsidian_trade_journals/assets/charts/<X>/<file>
        # so relative from gallery.md: ../../../assets/charts/<X>/<file>
        gallery_to_asset = f"../../../assets/charts/{rel_inside}"
        lines.append(
            f"| {i} | `{t['strategy']}` | {t['pair']} | {t['open_date'][:10]} | "
            f"{fmt_pct(t['profit_ratio'])} | +{t['mfe_pct']*100:.2f}% | "
            f"-{abs(t['mae_pct'])*100:.2f}% | `{t.get('outcome', '')}` | "
            f"`{t.get('exit_diagnosis', '')}` |"
        )
        embeds.append(
            f"### {i}. {t['strategy']} — {t['pair']} · {fmt_pct(t['profit_ratio'])}\n\n"
            f"![{t['strategy']} {t['pair']}]({gallery_to_asset})\n\n"
            f"- outcome: `{t.get('outcome', '')}`  ·  exit_diagnosis: `{t.get('exit_diagnosis', '')}`\n"
            f"- MFE +{t['mfe_pct']*100:.2f}%  ·  MAE -{abs(t['mae_pct'])*100:.2f}%\n"
            f"- exit_reason: `{t.get('exit_reason', '')}`\n"
        )
    lines.append("")
    lines.append("## Charts")
    lines.append("")
    lines.extend(embeds)
    lines.append("")
    lines.append("## See also")
    lines.append("")
    lines.append("- [[../../../wiki/synthesis/cross-strategy-trade-library|Cross-Strategy Trade Library]]")
    lines.append("- [[../../README|Research index]]")
    lines.append("- [[../../../Training Journal/master|Training Journal master]]")
    path.write_text("\n".join(lines) + "\n")
    return path


def relocate_existing_chart_refs() -> int:
    """For every md file in the vault, find image embeds pointing at
    ../../../data/all_trade_charts/... ; copy the PNG into vault and rewrite the path."""
    rewrite_re = re.compile(r"!\[([^\]]*)\]\(([^)]+/data/all_trade_charts/[^)]+\.png)\)")
    count = 0
    files_touched: set[Path] = set()
    for md in VAULT.rglob("*.md"):
        text = md.read_text()
        if "data/all_trade_charts/" not in text:
            continue
        new_text = text
        for m in rewrite_re.finditer(text):
            full_path = m.group(2)
            # Extract the part after "data/all_trade_charts/"
            idx = full_path.find("data/all_trade_charts/")
            relpath = full_path[idx + len("data/all_trade_charts/"):]
            # Copy into vault
            new_chart_path = copy_chart(f"all_trade_charts/{relpath}")
            if new_chart_path is None:
                continue
            # Compute relative path from this md to new chart path
            try:
                rel = Path(*[".."] * len(md.relative_to(VAULT).parts[:-1])) / new_chart_path.relative_to(VAULT)
            except ValueError:
                continue
            new_embed = f"![{m.group(1)}]({rel.as_posix()})"
            new_text = new_text.replace(m.group(0), new_embed)
            count += 1
        if new_text != text:
            md.write_text(new_text)
            files_touched.add(md)
    return count, len(files_touched)


def main() -> int:
    rows = load_rows()
    tag_counts = Counter(r.get("enter_tag", "") for r in rows)
    top_tags = [t for t, _ in tag_counts.most_common(TOP_N_PRIMS + 1) if t]  # skip blank
    top_tags = top_tags[:TOP_N_PRIMS]
    print(f"top-{TOP_N_PRIMS} enter_tags:")
    for t in top_tags:
        print(f"  {tag_counts[t]:>5}  {t}")
    print()

    ASSETS.mkdir(parents=True, exist_ok=True)
    GALLERIES.mkdir(parents=True, exist_ok=True)

    by_tag: dict[str, list[dict]] = defaultdict(list)
    for r in rows:
        by_tag[r.get("enter_tag", "")].append(r)

    galleries_written = 0
    charts_copied_for_galleries = 0
    for tag in top_tags:
        sample = pick_representative(by_tag[tag], TRADES_PER_GALLERY)
        for t in sample:
            new_path = copy_chart(t.get("chart_path", ""))
            if new_path:
                charts_copied_for_galleries += 1
        gpath = write_gallery(tag, sample)
        galleries_written += 1
        print(f"  wrote {gpath.relative_to(VAULT)}  ({len(sample)} trades)")

    # Relocate existing chart references in OTHER pages (cross-strategy library, market pages, etc.)
    rewrites, files = relocate_existing_chart_refs()
    print(f"\nrelocated {rewrites} chart embeds across {files} md files")
    print(f"total charts copied into vault: ~{charts_copied_for_galleries + rewrites} (unique count may be lower)")

    # Build a top-level Research/galleries index
    idx = GALLERIES / "README.md"
    idx_lines = [
        "---",
        "title: Prim Galleries",
        "type: gallery-index",
        "updated: 2026-04-25",
        "---",
        "",
        "# Prim Galleries",
        "",
        f"Outcome-stratified trade galleries for the top-{TOP_N_PRIMS} `enter_tag`s in the "
        f"3,300-trade library. Phase 1 — top-5 only, full backfill deferred.",
        "",
        "| Prim | Trades shown | Total in library |",
        "|---|---:|---:|",
    ]
    for t in top_tags:
        idx_lines.append(f"| [[{t}/gallery|{t}]] | {min(TRADES_PER_GALLERY, len(by_tag[t]))} | {tag_counts[t]} |")
    idx_lines.append("")
    idx.write_text("\n".join(idx_lines) + "\n")
    print(f"\nindex: {idx.relative_to(VAULT)}")
    print(f"\nDONE. {galleries_written} galleries written.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
